export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';

export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';

export const UPLOADING_FILE = 'UPLOADING_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';

export const CLEAR_STATE = 'CLEAR_STATE';
export const ADD_PASSWORD = 'ADD_PASSWORD';
export const ADD_DOWNLOAD = 'ADD_DOWNLOAD';

CLEAR_STATE